/** @type {import('tailwindcss').Config} */
const appFontStack = ['"Manrope"', "sans-serif"]

export default {
	darkMode: "class",
	content: [
		"./index.html",
		"./src/**/*.{js,ts,jsx,tsx}",
	],
	theme: {
		extend: {
			colors: {
				"on-secondary-fixed": "#6a0e17",
				"on-primary-fixed": "#000000",
				"surface-tint": "#ac2c00",
				"surface-variant": "#ffd2d0",
				"outline-variant": "#e09c99",
				"secondary-fixed": "#ffc3c0",
				"surface-container-highest": "#ffd2d0",
				"secondary-container": "#ffc3c0",
				"error": "#b31b25",
				"surface-container-low": "#ffedeb",
				"surface": "#fff4f3",
				"on-secondary-fixed-variant": "#922d30",
				"surface-bright": "#fff4f3",
				"on-background": "#4e2121",
				"on-primary-fixed-variant": "#581200",
				"on-primary": "#ffefec",
				"on-primary-container": "#480d00",
				"tertiary-container": "#e094f8",
				"primary-fixed": "#ff7852",
				"on-error": "#ffefee",
				"on-surface-variant": "#834c4b",
				"surface-container-lowest": "#ffffff",
				"tertiary": "#823e9b",
				"background": "#fff4f3",
				"error-container": "#fb5151",
				"error-dim": "#9f0519",
				"inverse-primary": "#ff5624",
				"tertiary-fixed": "#e094f8",
				"secondary-fixed-dim": "#ffafac",
				"surface-dim": "#ffc7c4",
				"surface-container-high": "#ffdad8",
				"outline": "#a26765",
				"on-tertiary-fixed-variant": "#5c1675",
				"inverse-surface": "#240304",
				"on-secondary-container": "#852328",
				"primary-dim": "#972500",
				"surface-container": "#ffe1e0",
				"primary": "#ac2c00",
				"secondary": "#a0373a",
				"inverse-on-surface": "#cd8c8a",
				"primary-fixed-dim": "#ff5d2e",
				"primary-container": "#ff7852",
				"on-tertiary-fixed": "#2d003e",
				"on-surface": "#4e2121",
				"tertiary-fixed-dim": "#d187e9",
				"on-error-container": "#570008",
				"on-secondary": "#ffefee",
				"secondary-dim": "#902c2f",
				"on-tertiary": "#ffedfe",
				"tertiary-dim": "#75318e",
				"on-tertiary-container": "#52076c",
				"cusens-primary": "#ff7852",
				"cusens-primary-hover": "#ff5d2e",
				"cusens-accent": "#ffc3c0",
				"cusens-bg": "#fff4f3",
				"cusens-surface": "#ffffff",
				"cusens-surface-muted": "#ffdad8",
				"cusens-border": "#e09c99",
				"cusens-text-primary": "#4e2121",
				"cusens-text-secondary": "#834c4b",
				"cusens-dark": "#240304",
				"cusens-dark-muted": "#4e2121",
				"cusens-dark-hover": "#581200",
				"cusens-blue": "#ff7852",
				"cusens-green": "#ff7852",
				"cusens-green-light": "#ffdad8"
			},
			fontFamily: {
				sans: appFontStack,
				body: appFontStack,
				label: appFontStack,
				heading: appFontStack,
				display: appFontStack,
				headline: appFontStack,
			},
			borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
		},
	},
	plugins: [],
}
