export type {
  ExtrasDto,
  MealDto,
  MealSizeDto,
  PageResponse,
  Restaurant,
  RestaurantBadge,
  RestaurantBadgeDto,
  RestaurantRequestDto,
  RestaurantResponseDto,
  RestaurantReview,
  RestaurantReviewDto,
  SectionRequestDto,
  SectionResponseDto,
} from '../../shared/types';
